stages:
  - build
  - test

create_file:
  stage: build
  image: alpine
  script:
    - echo "Building..."
    - mkdir build
    - touch build/testfile.txt
  artifacts:
    paths:
      - build/
    expire_in: 1h  

test_file:
  stage: test
  image: alpine
  dependencies:
    - create_file  
  script:
    - if [ -f build/testfile.txt ]; then echo "Test passed!"; else echo "Test failed!"; exit 1; fi
